### ISSUE TITLE
Same secret multiple times in the same file

### ISSUE THREAD

**Issue by gustavotabares** [Yelp/detect-secrets#134]
Hello,

I'm trying to scan using `detect-secrets --all-files` and I noticed that the tool does not detect multiple instances of the same secret in a single file. It will simply flag the first instance found. The comment located [here](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/potential_secret.py#L50-L53) makes me believe that this is by design. Is it possible to change this behavior or is the tool not designed for this?

**Comment by KevinHock** [comment]
Hi @gustavotabares, @domanchi  and I have had [some discussions around this](https://github.com/Yelp/detect-secrets/pull/86#issuecomment-446338402). However we've kind of punted dealing with this particular issue in the recent past. Line numbers are purposely not part of the secret hash because when lines move around we don't want to re-alert, but I don't see why we couldn't have a count of the secret and keep track of it that way. It is kind of a nice-to-have IMO though.

Thanks for making this a GitHub issue 👍 In summary it is possible to change this behavior, it's just that we haven't addressed it yet.

**Comment by domanchi** [comment]
This is heavily similar to https://github.com/Yelp/detect-secrets/issues/53, so closing this issue in favor of the older one.
