### ISSUE TITLE
Refactor to improve ease of developing additional plugins

### ISSUE THREAD

**Issue by justineyster** [Yelp/detect-secrets#154]
I just made my first PR yesterday in IBMs `detect-secrets` fork to add a plugin for Artifactory credentials (which I plan to contribute here, too).

My first impression is that it is not optimal for development efficiency to have to edit 8 files in disparate locations to add one plugin. 

I would think that creating one file under `detect_secrets/plugins` and one under `tests/plugins` should be roughly sufficient. This design could be achieved by using some kind of global `config.py` file that lists all the plugins and their attributes like whether they are default or not, perhaps within a dictionary. Tests could then reference this dictionary instead of needing to hardcore additional plugins, like in `tests/main_test.py` and `tests/pre_commit_hook_test.py`.

The information that's currently in the `PluginOptions` class of `detect_secrets/core/usage.py` could also be included in this dictionary to avoid needing to edit `detect_sectets/core/usage.py` and `tests/core/usage_test.py`.

I believe this change would allow a developer to edit just 4 files instead of 8 to add a plugin, those being: `detect_secrets/plugins/<new_plugin>.py`, `tests/plugins/<new_plugin_test>.py`, `README.md`, and the `config.py` file.

If this design sounds reasonable to the codebase owners, I can begin working on a PR to refactor as described above.

**Comment by domanchi** [comment]
SGTM.

Refactoring for developer efficiency and code clarity is always welcome.

**Comment by KevinHock** [comment]
Hi @justineyster, did you folks have any luck with this? Just curious. As I feel it might be good to have before we add in Trufflehog regex's or the `How bad can it git?` paper regexes.

**Comment by justineyster** [comment]
@KevinHock Perhaps we could have a quick design/delegation/timeline conversation around this soon? What do you think? Sounds like you're in a similar situation as us, in expanding detectors.

**Comment by KevinHock** [comment]
Sorry for the lack of reply, https://github.com/Yelp/detect-secrets/pull/248 helped this with DRYness a lot.

I can make another issue for a "bring your own regex" plugin, as that would be pretty helpful, e.g. [`shhgit`](https://github.com/eth0izzle/shhgit/blob/master/config.yaml) does this well, and there's no reason we can't do what they do + add verify functions.

There's also the idea of "bring your own plugin" entirely, in case you wanted to make e.g. a new entropy plugin with more metacharacters, or a new keyword type detector, and either keep it company specific or use it/tune it privately before contributing upstream.

I think we could possibly refactor the existing regex plugins into default settings for a "bring your own regex" plugin, I'd be happy to try my hand at this and see how it goes. I would like to prioritize it over a 'bring your own plugin' in the short-term, as it has a bigger impact and is more immediately helpful to users.

The only dangers in 'bring your own regexes' is that, if a user didn't use our default config file, they would have to realize the backwards compatibility considerations of changing a regex or secret type after they have a bunch of baseline's with output of a previous run with a different regex or secret type name, e.g. like when #26 made it so that we removed all existing high-entropy secrets, and re-added them with different potential secret hashes, (due to a new `secret type`) even though they were the same exact secrets.

**Comment by domanchi** [comment]
Closing as done. Since the last comment, we've:

1. Added the ability for developers to bring their own plugins
2. Created `RegexBasedDetector` base class that allows for minimal additions to add a new plugin (see https://github.com/Yelp/detect-secrets/pull/359/files for a great example)
3. Refactored the `--disable-plugin` functionality and plugin discoverability + initialization logic to actually be sane
4. Architected an automatic upgrade process to make baselines more backwards compatible (see https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/upgrades.md)
