### ISSUE TITLE
Clarification regarding the baseline file and auditing

### ISSUE THREAD

**Issue by lirantal** [Yelp/detect-secrets#173]
hola fellas 👋, nice work with the project, I like the flexibility and the de-coupled architecture of managing secrets. 

Some questions I was hoping to clarify with your help:
* if a baseline file exists and provided to the precommit hook script, regardless of the `is_secret` property, an entry for a secret will be considered as a whitelist. Is this an expected behavior?
* Assuming the above is true, it leads me to question the purpose of the `is_secret` property - is that supposed to be served as a manual review of secrets and their status? As it doesn't seem to provide any other integrated functionality besides being metadata that the user sets.

I'd be happy to also learn what is the expected methodology of maintaining the baseline secrets. Is this expected to be created during a build? I would think that a build that mutates the git history directly is an anti-pattern, so perhaps a build step that triggers a pull request but not sure if this is aligned with expected usage of the baseline file.

Thanks!

**Comment by domanchi** [comment]
Hey @lirantal,

Good questions! Hopefully, my explanation of some design rationale will be able to answer these.

The pre-commit hook was designed to prevent secrets from entering the code base, during commit time. This was designed with developer velocity in mind, with the implicit assumption that the security team would be more concerned about secrets in code than the regular developer. Therefore, we did not want to block developers from pushing code if we already knew about a secret -- otherwise, that will implicitly make secrets in source code a P0 and block all development until fixed.

With this in mind, the `is_secret` field is a "manual" addition with the `audit` functionality. In essence, it is saying, "a human has looked at this, and determined whether action needs to be done". Note that this still does not enforce action to be done *immediately* (and IMO, shouldn't), so should not block the pre-commit hook.

You are right that this metadata addition does not provide other functionality in this library alone. However, this library was never intended to be used alone! At a macro scale (e.g. [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server)), it allows the security team to:

1. Distribute the auditing process to developers from other teams, to horizontally scale efforts of this very manual auditing process.
2. Collect metrics on true/false positives, as well as number of secrets left to be audited.
3. Train our heuristic detectors (e.g. `KeywordDetector`) and customize limits (e.g. `HighEntropyStringsPlugin`) for improved accuracy.

Maintenance of the baseline secrets comes free with the installation of the pre-commit hook, and mutates it if there are any changes to it. If your build process runs all pre-commit hooks, there's an added benefit that builds will fail if new secrets are added.

**Comment by KevinHock** [comment]
@domanchi  W/r/t this issue and https://github.com/Yelp/detect-secrets/issues/175, where do you think we should put these greater-level-of-detail explanations? Perhaps a `docs/` directory or a readthedocs.org, I just know github issues probably aren't the right place

**Comment by domanchi** [comment]
It's a good point. I don't know best practices for this.

A lot of documentation I've read surrounds itself with *what* and *how* to interact with the library, not *why* design decisions were made.

**Comment by MVrachev** [comment]
> @domanchi W/r/t this issue and #175, where do you think we should put these greater-level-of-detail explanations? Perhaps a `docs/` directory or a readthedocs.org, I just know github issues probably aren't the right place

GitHub pages are really useful for those kind of stuff.
We use them in our [project](https://vmware.github.io/precaution/) and they have ready to use themes and markdown support.
Other famous project which uses them is TSLint - typescript linter: http://palantir.github.io/tslint/

To be honest because GitHub pages are build on every commit merged into the master branch, sometimes happens that the builds are failing.

**Comment by dgzlopes** [comment]
That's a great idea! But maybe following the Pythonic way of using https://readthedocs.org/ and doing the /docs as @KevinHock said is more straightforward.  Whatever... Maybe this should be discussed on a new issue as here seems a little bit offtopic.

**Comment by lirantal** [comment]
Thanks for explaining. I think that it is valuable to explain the `why` in the docs for tools like this which are also encompassing a flow and behind-the-scenes architecture as it helps understanding why things work the way they do.

**Comment by thekbb** [comment]
This is a super legit discussion. Thank you, and consider beverages owed to all on the thread.

It explains some of the reasons this tool is fitting into my work. It's *developer* focused and shifts left really well. I have a large desire to not only prevent secrets from hitting github - but I require a control in the pipeline to at least verify that the local check wasn't bypassed and we made an attempt to find secrets.

@domanchi how'd you feel about a `--require-audit` option? I can write up the issue and make the PR, but in essence I want to run this on a github status check:
```
git ls-files | grep -v .secrets.baseline | xargs detect-secrets-hook --baseline .secrets.baseline
```
_And_ be able to specify `--require-audit`, which would fail the build if there was a secret in the baseline that didn't have `is_secret` defined or `is_secret == true`.
I don't want detect-secrets to be my only tool - but I want to have the status check be something not entirely unlike what i run on my mac.

I'm all serverless and don't have any ec2 instances, vpc, security groups - so ironically running https://github.com/Yelp/detect-secrets-server would cause me to spend calories on security concerns I've avoided.

**Comment by domanchi** [comment]
@thekbb : this is a great idea. Let's add it to the pre-commit hook in the v1 branch.

**Comment by djgoku** [comment]
@thekbb I don't see that this was added.

I am also in need of `--require-audit` to make `detect-secrets scan --baseline .secrets.baseline --require-audit` exit with a non-zero status if there are secrets that haven't been verified. That is, if I am understanding what I am reading from the discussion.
