### ISSUE TITLE
[Question] What does "hashed_secrets" stands for in the output?

### ISSUE THREAD

**Issue by MVrachev** [Yelp/detect-secrets#175]
There is no documentation about this and the name is not really self-explanatory.

**Comment by KevinHock** [comment]
I agree it is one of the more confusing things in the codebase,`hashed_secret` vs. `secret_hash` etc.

Succinctly it is the hash of the content of the secret (`secret_hash`), the plugin that found it (`secret_type`) and the name of the file the secret is in (`filename`). It does not include line number since that would cause the hash to change all the time.

#### The way `hashed_secret` gets set is:
https://github.com/Yelp/detect-secrets/blob/38b559c442b20205436c57bb7503c59cc815464c/detect_secrets/core/potential_secret.py#L71
->
https://github.com/Yelp/detect-secrets/blob/38b559c442b20205436c57bb7503c59cc815464c/detect_secrets/core/potential_secret.py#L47
->
https://github.com/Yelp/detect-secrets/blob/38b559c442b20205436c57bb7503c59cc815464c/detect_secrets/core/potential_secret.py#L56-L63
->
https://github.com/Yelp/detect-secrets/blob/38b559c442b20205436c57bb7503c59cc815464c/detect_secrets/core/potential_secret.py#L88-L94
->
https://github.com/Yelp/detect-secrets/blob/38b559c442b20205436c57bb7503c59cc815464c/detect_secrets/core/potential_secret.py#L53

This `fields_to_compare` part is especially important, e.g. [one time we changed a secret type](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#boom-breaking-changes-3) and [it broke all the baselines](https://github.com/Yelp/detect-secrets/issues/37) 😁

**Comment by domanchi** [comment]
Something we definitely didn't want to happen is create a file with all secrets from a repository extracted. This way, you wouldn't be able to share these baselines around, because you'd be just contributing to the problem (secrets in source code).

The `hashed_secret` field is just the hash of the secret value, to accommodate for this use case.

**Comment by MVrachev** [comment]
Thank you for your answers!
I understand your motivation and idea now.
