### ISSUE TITLE
document `audit --diff` functionality in CONTRIBUTING.md

### ISSUE THREAD

**Issue by domanchi** [Yelp/detect-secrets#190]
There's a super cool feature that helps plugin developers create plugins easier, by comparing to a known baseline.

```
$ detect-secrets audit --diff old_baseline.json new_baseline.json
```

We should probably document this, for better discoverability and developer happiness.

**Comment by KevinHock** [comment]
Same for --audit display, I think since we're probably never gonna get around to it, that we just paste in the --help output to the README. Our stance was that if someone wants to find these things --help is easy enough but I want to say I've seen 2+ GitHub comments of people struggling with what could have been alleviated by having --help in the README.

**Comment by domanchi** [comment]
Wrote much more detailed descriptions in https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/audit.md. Closing as done.
