### ISSUE TITLE
Not an issue but not sure where to ask this question

### ISSUE THREAD

**Issue by c0debreaker** [Yelp/detect-secrets#225]
Aside from Artifactory, AWS, Slack, Stripe, Mailchimp, what else can detect-secrets detect? We have our own confidential strings that we would like to monitor. An example value would be `udxID_7824252555234`. Can `detect-secrets` be configured so that it will also detect this string? But of course, we don't want to block it if this string is found in README files.

Also, do you see any issue since I'm using detect-secrets on the server side as a git hook? This way, developers won't be able to bypass it. If there are issues, we can easily disable it on the server since we have control on our git servers.

**Comment by domanchi** [comment]
Using `detect-secrets` on the server-side is a nuanced challenge. Due to expected false positives, hard blocking on identification of an issue may create more developer friction than you want. Unless of course, you **enforce** the use of the pre-commit hook, to make sure your blocking git hook will pass.

There are two alternatives:

1. Use the [`detect-secrets-server`](https://github.com/Yelp/detect-secrets-server) library to scan changes to all repositories on a regular basis, and create tickets through that.

2. Use the git hook as a non-blocking pre-receive hook.

I recently saw this development pattern, and it looked really promising:

```
$ git push origin HEAD
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 6.21 KiB | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote:
remote: GitHub found 2 vulnerabilities on domanchi/devtools's default branch (1 high, 1 moderate). To find out more, visit:
remote:      https://github.com/domanchi/devtools/network/alerts
remote:
To github.com:domanchi/devtools.git
   936bac2..5699a37  HEAD -> master
```

If you have confidential strings, my suggestion is to fork this module. We don't currently support the use of [`RegexBasedDetector`](https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/base.py#L196) with arbitrary user input.

**Comment by c0debreaker** [comment]
Maybe instead of us devops blocking the git push right away, we'll just warn the user on the output as well as populate a database that will be executed by our server pre-receive hook. The log will contain the repo and the file that detect-secrets that generated. I can write a user interface that can be used to render the reports. From that web application, we can find out if dev teams have been committing confidential info to their repo.
