### ISSUE TITLE
Bad False Positive

### ISSUE THREAD

**Issue by ls-philippe-gamache** [Yelp/detect-secrets#273]
In the Keyword file, you have 'password' patern, but it also in the false positive list. 

In AWS it detect: access_key_id but not secret_access_key that was in the next line.

**Comment by KevinHock** [comment]
The false positive set is for the secret value itself, the keywords have a different purpose. `password = tangerine3782934` vs. `[some key word] = 'password'`, the latter we purposely don't alert on. Why is that a bad thing?

Can you share the syntactic context for the AWS file? Was it e.g. `secret_access_key = [the value]` or `secret_access_key: "[the value]"` or something else? Can you share the file extension?

**Comment by KevinHock** [comment]
Going to close this for now but definitely happy to discuss more if I can get some more information on the questions above 👍

**Comment by nfriacowboy** [comment]
Hi I facing  a situation with code in TypeScript, take this code as exemple:

```
export const config = {
  name: 'connectionName',
  password: process.env.DB_USER_PWD,
  database: process.env.DB_NAME
};
```
run the command:
`detect-secrets scan > .secrets.baseline`

and them 
` pre-commit run`

and I get the error refering to the line 9 (that in the file is the line were the "password" string is)

if I change to 
```
export const config = {
  name: 'connectionName',
  password : process.env.DB_USER_PWD,
  database: process.env.DB_NAME
};
```
and I run the command:
`detect-secrets scan > .secrets.baseline`

on the .secrets.baseline file we can find the reference to the 
"src\\helpers\\helperFile.ts": [
      {
        "hashed_secret": "37117cf258c07c6e0645e1bac09059be1cc42bce",
        "is_verified": false,
        "line_number": 9,
        "type": "Secret Keyword"
      }
    ],
and them the command
` pre-commit run`
pass successfully.

So I have 2 questions:

- Should the string "password:" be added to the FALSE_POSITIVES list?
- Is there a way to extend this list without having to add the `pragma: allowlist secret` ?

**Comment by KevinHock** [comment]
On my phone so apologies for sloppiness:

1st question: the space is messing with the keyword: regex, the right hand side can be added to the FALSE_POSITIVES list. The RHS, which it thinks is the secret, should be highlighted during audit mode.


2nd question: —line-exclude, or —no-keyword-detector

**Comment by KevinHock** [comment]
I’d welcome a PR Adding a “startswith process.ENV.” check inside keyword.py, in that way all env vars accessed this way won’t be reported.

Alternatively, not sure what file extension typescript uses, but perhaps we can require keyword secrets have quotes (2 line PR). Not sure how typescript works though.

**Comment by KevinHock** [comment]
(Back on Desktop)


Okay it seems like we can add typescript to https://github.com/Yelp/detect-secrets/blob/2b92ed6ed2b58b799a3d748c17ebd6c81b17d26c/detect_secrets/plugins/keyword.py#L244-L251 and https://github.com/Yelp/detect-secrets/blob/2b92ed6ed2b58b799a3d748c17ebd6c81b17d26c/detect_secrets/plugins/common/filetype.py#L5-L35

This should greatly reduce all keyword detector false-positives for typescript files.

**Comment by nfriacowboy** [comment]
Hi @KevinHock , hope you had a great weekend and thanks for your kick answer.

I didn't have the opportunity to check your suggestions with the required care, and right now I  did the changes you suggested. As soon I have something I will share it.

Thanks

**Comment by nfriacowboy** [comment]
Hi again @KevinHock  i figure it out what is happening.

It took a while because of the erratic pattern i was getting.

Well I added a new repo under my [github account](https://github.com/nfriacowboy/ds-test) for testing and sharing purposes

I tested the same code changes on a both mac and windows.
The issue happens on windows when the files have keywords and are inside folders, looks like is related with he windows backslash folder separator on the .secrets.baseline file.
Example:
 On mac the reference to the file is this:
`"scripts/otherfolder/test.json": [`

on windows after recreate the .secrets.baseline the line comes to this:
  `"scripts\\otherfolder\\test.json": [`

and when executing the pre-commit run command for some reason it fail the match of the file path with the reference on the **.secrets.baseline** 

on the project i have the same files that are inside scripts/otherfolder/ on the root to make the same changes on both files and the result.

My test procedure is this:
1 – make same changes on test.* files on root and inside the folder scripts/otherfolder/
2 – execute command` detect-secrets scan > .secrets.baseline`
3 – execute command `git add .`
4 – execute command `pre-commit run`

Thanks for your time

**Comment by nfriacowboy** [comment]
Hi again,

I could use some help on this one... 

Doing some searches i found this article:
https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

and the guy was referring to the  PureWindowsPath,

i didn't find any reference on the code of detect-secrets to that lib, 

I not a python developer so for much I want to put hands on the code is a bit complicated, so for any one experienced on python what do you think about this suggestion to handle this bug:

during the pre-commit execution when reading the path from the .secrets.baseline file check if the path has backslash \, if it has build the path using the suggestion from the article, something like this:

```
filename = Path(path_to_source_code_file_in_baseline)

# Convert path to Windows format
windowsPath= PureWindowsPath(filename)
```

ideas, sugestions... 

@KevinHock should this be another post or open this one to perhaps help someone else?
