### ISSUE TITLE
Tool not detecting anything.

### ISSUE THREAD

**Issue by JGutierrezG** [Yelp/detect-secrets#276]
Hello i'm testing the tool, and for some reason it is not detecting any kind of secret, token or password.

I've been using different kind of high entropy auto generated values, and can't make it work.

Im pretty sure that i made a good installation, but at every scan it just says Passed.

This is an example of what kind of keys im using to test:

> 
   15 {p~hqHGE&x:q~skc~X@dkdblwvbC)JsW4F;40.;0(o}{<6@25P~X-E$
   14 $
   13 $
   12 'wJY+a9Z`&S;?{$w#FSLN8%ZMzEZ-?04xzmO>6X)TMzW1O7sXHe&[k~v;ERdg`:xi'$
   11 '00wJY+a9Z`&S;?{$w#FSLN8%ZMzEZ-?04xzmO>6X)TMzW1O7sXHe&[k~v;ERdg`:xi'$
   10 'KCCCKAwJY+a9Z`&S;?{$w#FSLN8%ZMzEZ-?04xzmO>6X)TMzW1O7sXHe&[k~v;ERdg`:xi'$
    9 $
    8 $
    7 $
S>  6 { $
S>  5  "access_token":"eyJz9sdfsdfsdfsd", $
S>  4  "refresh_token":"dn43ud8uj32nk2je", $
    3  "id_token":"dmcxd329ujdmkemkd349r",$
S>  2  "token_type":"Bearer", $
    1  "expires_in":3600$
  19  }$
Any clue?

**Comment by manesioz** [comment]
Can you go over how you configured your repo? 
Did you generate a `.secrets.baseline` file, audit the file, and then commit to the repo? 
After which did you create a `.pre-commit-config.yaml` file according to your specifications and run `pre-commit install`?

**Comment by JGutierrezG** [comment]
@manesioz  Hello!
Yes, i made all the installation process, as it is explained in the repo, generated the .secrets.baseline, audited the file, made all the pre-commit process... im sure that i followed all the steps.
I added a new file with a certificate and it detects the certificate, so... i think that the tool works but not for the keys and passwords above.

**Comment by domanchi** [comment]
Hi @JGutierrezG,

I'm having a hard time parsing your example (you might have had an unclean vim copy?), but a handy way to debug is using the adhoc scanning feature.

For example:

```
$ detect-secrets scan --string "eyJz9sdfsdfsdfsd"
AWSKeyDetector         : False
ArtifactoryDetector    : False
Base64HighEntropyString: False (2.703)
BasicAuthDetector      : False
CloudantDetector       : False
HexHighEntropyString   : False
IbmCloudIamDetector    : False
IbmCosHmacDetector     : False
JwtTokenDetector       : False
KeywordDetector        : False
MailchimpDetector      : False
PrivateKeyDetector     : False
SlackDetector          : False
SoftlayerDetector      : False
StripeDetector         : False
TwilioKeyDetector      : False
```

This suggests that the `HexHighEntropyString` plugin does not catch it (since it has characters that do not fall in the hex character range), and the `Base64HighEntropyString` plugin thinks that it's too low of an entropy limit to flag on (2.703).

You can do a similar thing with values such as `'wJY+a9Z&S;?{$w#FSLN8%ZMzEZ-?04xzmO>6X)TMzW1O7sXHe&[k~v;ERdg:xi'`:

```
$ detect-secrets scan --string 'wJY+a9Z&S;?{$w#FSLN8%ZMzEZ-?04xzmO>6X)TMzW1O7sXHe&[k~v;ERdg:xi'
...
Base64HighEntropyString: False
```

Here, the `Base64HighEntropyString` plugin doesn't even give an entropy limit. This means that the characters in the secret does not match the `Base64HighEntropyString` plugin, like the first example listed.

Does this answer your question?

**Comment by benjguin** [comment]
I also had issues with secrets detection, especially a difference between detect-secrets scan --string and detect-secrets-hook. I posted the question [here in StackOverflow](https://stackoverflow.com/questions/64388788/difference-between-detect-secrets-and-detect-secrets-hook-results) which may be a better location for such a discussion.

**Comment by domanchi** [comment]
StackOverflow question has been answered. Closing as done.
