### ISSUE TITLE
Consider adding a generic Regex plugin that takes a custom rules file

### ISSUE THREAD

**Issue by nightwatchcyber** [Yelp/detect-secrets#297]
Some of the other tools such as gitleaks, trufflehog, etc. take in a custom rules file with regex patterns. Consider adding a plugin like that which would be a lightweight way to customize the tool without making custom plugins (like #291). This maybe a good alternative for some use cases.

**Comment by nightwatchcyber** [comment]
I can try putting together a PR

**Comment by KevinHock** [comment]
cc @domanchi for opinions.

I think this is a side-effect of different audiences wanting different things, some people (e.g. pentesters) will want the lightweight config option -- others (stringent engineers) will think custom plugins encourages best-practices, and that best-practices should always be strongly encouraged.

I guess the question that should maybe decide this is: would we include a config file of regexes by default? I think our answer to this is No. Because we'll always want tests. I remember there was some [truffleHog regex](https://github.com/dxa4481/truffleHogRegexes/blob/master/truffleHogRegexes/regexes.json) that had a weird length requirement. 
The ["fb" followed by anything regex that gitLeaks](https://github.com/zricethezav/gitleaks/blob/0faebdefea7831d12114e9a798907d1e168314b6/config/default.go#L26) has is similar. Tests would always help clearly display what it does and does not intend to catch.

Implementation-wise, it may be not be super straightforward to dynamically generate classes that inherit from `RegexDetector`, and have a `secret_type` set to the name of the regex in the config file, although it is totally do-able.

The problem is also that with verification, that has to be written in Python. And we ideally want a `verify` method, because other secret detection tools don't have that AFAIK.



I do have this in my notes
```
Plugins to make
     "Facebook Secret Key"
     "Facebook Client ID"
     "Facebook access token"
     "Github"
     "Google API key"
     "Google Cloud Platform API key"
     "Google OAuth"
     "Google OAuth access token"
     "Twitter Secret Key"
     "Twitter Client ID"
     "LinkedIn Client ID"
     "LinkedIn Secret Key"
     "Heroku API key"
     "Mailgun API key"
```
as it would be really nice not to have any secret types found by other tools, and not by detect-secrets. I was gonna do the Facebook ones, but I don't know if we'll ever do the others 🤐 

This makes d-s strictly worse in some regards, we could of easily blindly copy others' regexes into new plugins, and not add verification, but the high-bar signal-to-noise bar we have for plugins is also kind of a good thing.

**Comment by KevinHock** [comment]
_An aside: I can't add labels to GitHub issues anymore, just throwing that out there. If any current-Yelper wants to carry the prestigious Issue Labeler torch, feel free to._ 😁 😄

**Comment by nightwatchcyber** [comment]
Thanks for the quick reply!

The use case I am looking at is where an organization would want to customize this for their internal use with patterns and plugins suitable for them, but not something that can be shared with the outside world. Having a regex plugin that allows a list of patterns to be passed would facilitate an easy way to extend the tool without going through the hassle of writing a custom plugin for each use case, especially where there are dozens of patterns and not all of them have verification available (things like SSNs, internal passwords, etc). This would also encourage developers to add patterns to the rules file.

Of course, once # 291 is merged in since may not be needed since such plugin can be written outside the main code base and used by those that needed it :) Perhaps that is a better way to proceed?

**Comment by KevinHock** [comment]
I think it is. End-product for a custom plugin is 3 lines of Python, as opposed to 1 line in a config for this idea, (granted there may be a ton of plugins,) so I don’t think developers will mind much.

_Can no longer close issues_

**Comment by nightwatchcyber** [comment]
Will close this for now, since #291 will take care of this use case

**Comment by nightwatchcyber** [comment]
And thank you

**Comment by domanchi** [comment]
I agree with @KevinHock. Another point to note is that baselines are created with the intention of being able to be compared over time, as well as being human readable (for auditing purposes). If you just passed in a file with regexes, you would have to consider how to represent this.

For example, while a file hash of the regex file may suffice to achieve the first objective (comparable over time), it doesn't deal well with the second objective. One should be able to read the baseline, and know how to triage the results, and why the engine flagged them as such.

**Comment by nightwatchcyber** [comment]
@domanchi It is a good point. I was thinking of recording the patterns in the baseline as part of the configuration, same way hex_limit is done for "HexHighEntropyString" plugin. That doesn't address the use case of patterns changing.
