### ISSUE TITLE
Base64 with less than 44 character length

### ISSUE THREAD

**Issue by fourirakbar** [Yelp/detect-secrets#304]
Hi Team, 

I have a base64 string with less than 44 characters (only 37). In file **ibm_cloud_iam.py** only detect if equal or more than 44 characters. `secret = r'([a-zA-Z0-9_\-]{44}(?![a-zA-Z0-9_\-]))'` . How can I also detect it? Or maybe I can make a PR to bring it down to 37..

Please help me resolve it. Thank you!

**Comment by domanchi** [comment]
@fourirakbar : huh. That's curious: to verify, you're saying that you have an IBM cloud IAM token that's only 37 characters? Or just that you have a base64 string that you're hoping to catch with the `ibm_cloud_iam` plugin?

If it's the latter, you're kind of out of luck. The high entropy string is not catching it because it probably doesn't have enough entropy. You can modify your entropy limit with `--base64-limit`, but you would need to experiment to get ideal results (for a false positive / false negative trade-off). You can also see what the current limit is by using `detect-secrets scan --string "<SECRET>"`

**Comment by killuazhu** [comment]
@fourirakbar I’m interested to hear more your use case more. IBM Cloud IAM keys by default are 44 chars. I heard before that in some rare cases, you can set your own api key to any length string. That’s not something we would be able to catch. Since those are rare cases, I don’t think we should change the IAM key length away from 44.

**Comment by fourirakbar** [comment]
Hmm I think my key is rare, only have 37 char. Never mind, maybe I will try another way. Thanks!
