### ISSUE TITLE
Repeated secrets in a file are not being captured

### ISSUE THREAD

**Issue by shaikmanu797** [Yelp/detect-secrets#326]
@KevinHock According, to the comments [here](https://github.com/Yelp/detect-secrets/blob/masterdetect_secrets/core/potential_secret.py#L54-L56) if any secret is found more than once that occurrence is ignored. A re-scan had to be performed after fixing the first occurrence to detect the leftover secrets and so on.

Instead, I would suggest adding line number as prefix salt before hashing to make it unique.

https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/potential_secret.py#L59-L60

```python
def set_secret(self, secret, salt=None):
   if salt is None:
      salt = self.lineno
   self.secret_hash = self.hash_secret(f"{salt}{secret}")
  ...
```

**Comment by shaikmanu797** [comment]
@KevinHock any suggestion for above.

**Comment by KevinHock** [comment]
>A re-scan had to be performed after fixing the first occurrence to detect the leftover secrets and so on.

Sorry to hear that 😞 

It is intentional that line numbers are not counted, as in most use-cases it would be annoying for a user if the lines changed around. At least that is the case for pre-commit hooks, for e.g. arc, it only yells at the changed lines.

The way one would do this, is to add the line number to `fields_to_compare`, it makes it a lot more straightforward than the salt.


I'd be open to you adding this under a flag, so that it wouldn't be the default behaviour. Does that sound amenable to you @shaikmanu797?

Thanks so much for your interest in this project btw :D

**Comment by shaikmanu797** [comment]
@KevinHock, will come up with a PR to allow the `fields_to_compare` input from cli.

**Comment by lorenzodb1** [comment]
We're going to close this issue as it hasn't received any update in a very long time. Feel free to re-open it if you think it's still relevant.
