### ISSUE TITLE
detect-secrets-hook --baseline .secrets.baseline does not ignore excluded files

### ISSUE THREAD

**Issue by ammarshadiq** [Yelp/detect-secrets#351]
When I try to run this command on my cli
`detect-secrets-hook -v --baseline .secrets.baseline exclude_file.txt`

it stills scan `exclude_file.txt`, even though `.secret.baseline` contains the exclusion of that file:
```
"exclude": {
    "files": "exclude_file.txt|^.secrets.baseline$",
    "lines": null
  },
```

Am i using the wrong command format?

**Comment by domanchi** [comment]
Hi @ammarshadiq,

You're probably right -- this is a bug. However, this is inadvertently fixed in v1 through the [filters system](https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/filters.md).

The main difference is that pre-v1, both the pre-commit hook and the main scanning engine implemented slightly different logic. We can see that here: https://github.com/Yelp/detect-secrets/blob/68f3d5b7db41617da619190bddc52165682142a0/detect_secrets/main.py#L178. Over time, with new feature additions, this diverged -- as the tendency is with non-DRY code.

In v1, the scanning architecture was fundamentally changed, such that both the pre-commit hook and the main engine runs the same code. With this, they will also run the same filters, which will address this bug.

Thank you for reporting this. I'm going to close this as "Won't Fix" though, given that it's already fixed in v1.
