### ISSUE TITLE
version baseline schema independently from application

### ISSUE THREAD

**Issue by thekbb** [Yelp/detect-secrets#354]
Currently, the version of detect-secrets is backed into `.secrets-baseline`.  I run into issues on my team when users have different patch versions of detect-secrets, or the docker image that runs the pr status check lags behind.
Not every release changes how the baseline is written or read .

I propose the baseline schema has it's own semantic version, it only changes when it needs too.  Question to consider, would newer versions of the app be expected to read older schema versions?

**Comment by KevinHock** [comment]
>Not every release changes how the baseline is written or read

One thing to also consider, is changing a plugin can affect existing baselines in-so-much-as adding or removing the found secrets 🤔 , thought about in that way, I don't know how many d-s releases map to something that would affect baselines, but I'd say most of them do, just from memory https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md.

**Comment by KevinHock** [comment]
> I run into issues on my team when users have different patch versions of detect-secrets, or the docker image that runs the pr status check lags behind.

Why is this an issue though? I'm not sure I fully understand, aside from, like all other software, using the latest version is generally better.

**Comment by thekbb** [comment]
Oh, for sure I'd generally like them to use the latest version - but if they use `0.14.2` to generate a baseline,  and the docker image that runs the github status check has `0.14.1`,  the check fails.  You've given me food for thought, but generally I'd expect a patch bump to not break things.

**Comment by domanchi** [comment]
I agree that patch bumps should not break things. In the up-and-coming v1 release, I wrote an entire upgrade system to ensure backwards compatibility with baselines, as well as a structured method of how to think about when and what version to bump to. Check out more details: https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/upgrades.md

As such, I'm going to close this as "Won't Fix" -- partially because it's already fixed, but in a different way than the suggested method.
