### ISSUE TITLE
Hardcoded PHP passwords not found

### ISSUE THREAD

**Issue by match-dennismntgns** [Yelp/detect-secrets#404]
I did some tests and a number of passwords (e.g. in an array or constant) were not found in a php file:

Array example:

```
     array (
                                        'host' => self::processHost('database05'),
                                        'database' => 'test',
                                        'user' => 'test',
                                        'password' => 'tzlzhzgpazlvaffudrnkbhlkyawtgzc',
                                ),
```

Constants:

```
   const   DB_TEST_PWD = 'jex0`&?c950?\7$ya5',
               DB_PWD = 'plqudzxtlhchccoqfirgmqqzxpyyoik';
```

I've used the following command: `detect-secrets scan > .secrets.baseline`

**Comment by domanchi** [comment]
@BlueCanary-DM , what version of `detect-secrets` are you running? Have you tried using `detect-secrets scan --string` to see what the individual plugins report?

**Comment by BlueCanary-DM** [comment]
I'm running version 0.13.1 as I had the issue described here:
https://github.com/Yelp/detect-secrets-server/issues/62

**Comment by adityak80** [comment]
I am facing the same problem with PHP files, the following code is not caught by any of the plugins:
```
define('DB_GLOBAL_MASTER',
    array(
        'database' => 'GLOBAL_MASTER',
        'host' => 'xxx.xx.203.94',
        'port' => '1433',
        'username' => 'xxxxweb-xxadmin',
        'password' => '***@9mIn',
    )
);
```

Even _'password'_ is not flagged by KeywordDetector unless one removes the single quotes around the word _password_.

**Comment by jpdakran** [comment]
After doing some investigation on this issue. The issue with the array declaration is valid. The `=>` operator is not picked up by the keyword detect. I have added [567](https://github.com/Yelp/detect-secrets/pull/567) to fix this issue.

With respect to the `const` secrets noted above. The first secret (`DB_TEST_PWD`) is detected. The second secret (`DB_PWD`) indeed is not detected. However this is because it is filtered out by the `detect_secrets.filters.gibberish.should_exclude_secret`

This investigation was performed on detect-secrets v1.2.0
