### ISSUE TITLE
scan_files method in SecretsCollection class with parallel processing issue

### ISSUE THREAD

**Issue by KBiru** [Yelp/detect-secrets#570]
If the scan_files method is called with multiple files using scan_files("file1", "file 2") blueprint, it has serious infinite looping issue. The exact error comes from parallel processing but the sub process spawning continues - 
untimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module

One can stage the issue by using scan_files() method with multiple file name as arguments.

**Comment by ttibbel** [comment]
Hi @KBiru thanks for reporting this. I haven't been able to reproduce this issue on either macOS or Windows with detect-secrets 1.2.0. Can you confirm what OS you're using and the version of detect-secrets? Any other info you can provide to reproduce this issue would also be helpful. Thanks!

**Comment by KBiru** [comment]
Hi, I am using v1.2.0 of detect-secrets and the OS is windows 10.
So, the problem occurs when we pass more than 1 file name as argument to the scan_files function of SecretsCollection class.

**Comment by ttibbel** [comment]
Thanks for the additional information; I've been able to reproduce this issue on Windows 10 as well. 

This issue is specific to Windows and is mentioned in the Python [multiprocessing documentation](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods) (see the `Safe importing of main module` section). You'll need to make sure any Python scripts on Windows use the `if __name__ == '__main__':` entry point and then the `scan_files` function should work as expected.

Rewriting the simple example from the detect-secrets README for Windows would look like this:
```
from detect_secrets import SecretsCollection
from detect_secrets.settings import default_settings

def main():
    secrets = SecretsCollection()
    with default_settings():
        secrets.scan_file('test_data/config.ini')

    import json
    print(json.dumps(secrets.json(), indent=2))

if __name__ == "__main__":
    main()
```

Please let me know if that fix works for you and if so we can make a note in the README file.

**Comment by KBiru** [comment]
Hi @ttibbel ,

Thank you for the resolution, this seems about right. I got it to work properly now.
